[primary_control_plane]
192.168.1.211

[node]
192.168.1.212
192.168.1.213
192.168.1.214

[k8s_cluster:children]
primary_control_plane
node

[k8s_cluster:vars]
ansible_user=rocky
ansible_ssh_private_key_file="{{ lookup('env', 'K8SLAB_SSH_KEY') }}" # K8SLAB_SSH_KEY : variables d'environnement à créer pour le path du fichier ssh clé privée
